set_property IOSTANDARD LVCMOS33 [get_ports button1]
set_property IOSTANDARD LVCMOS33 [get_ports button2]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property IOSTANDARD LVCMOS33 [get_ports {colours[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {colours[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {colours[0]}]
set_property PACKAGE_PIN W19 [get_ports button1]
set_property PACKAGE_PIN T17 [get_ports button2]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]
set_property PACKAGE_PIN N19 [get_ports {colours[2]}]
set_property PACKAGE_PIN D17 [get_ports {colours[1]}]

set_property PACKAGE_PIN J18 [get_ports {colours[0]}]

set_property PACKAGE_PIN H1 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]

set_property PACKAGE_PIN U16 [get_ports {data_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {data_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {data_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {data_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {data_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {data_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {data_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[6]}]



set_property IOSTANDARD LVCMOS33 [get_ports enLED]
set_property PACKAGE_PIN L1 [get_ports enLED]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN V13 [get_ports {leds[0]}]
set_property PACKAGE_PIN V3 [get_ports {leds[1]}]
set_property PACKAGE_PIN W3 [get_ports {leds[2]}]
set_property PACKAGE_PIN U3 [get_ports {leds[3]}]

set_property PACKAGE_PIN W3 [get_ports avLED]
set_property IOSTANDARD LVCMOS33 [get_ports avLED]

set_property IOSTANDARD LVCMOS33 [get_ports {d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d[0]}]
set_property PACKAGE_PIN U14 [get_ports {d[6]}]
set_property PACKAGE_PIN U15 [get_ports {d[5]}]
set_property PACKAGE_PIN W18 [get_ports {d[4]}]
set_property PACKAGE_PIN V19 [get_ports {d[3]}]
set_property PACKAGE_PIN U19 [get_ports {d[2]}]
set_property PACKAGE_PIN E19 [get_ports {d[1]}]
set_property PACKAGE_PIN U16 [get_ports {d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {d[7]}]
set_property PACKAGE_PIN V14 [get_ports {d[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports enArrayLED]
set_property PACKAGE_PIN P1 [get_ports enArrayLED]

set_property IOSTANDARD LVCMOS33 [get_ports arrayStart]
set_property PACKAGE_PIN K2 [get_ports arrayStart]
