# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25.xci
# IP: The module: 'Prescaler25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prescaler25'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prescaler25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prescaler25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25.xci
# IP: The module: 'Prescaler25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prescaler25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prescaler25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/PROGHProjecten/PROGH2/Project_Besje/GameBesje/GameBesje.srcs/sources_1/ip/Prescaler25/Prescaler25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prescaler25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
